### ISSUE TITLE
not able to add to twine format

### ISSUE THREAD

**Issue by tekkkon** [cauli/TwineJson#12]
Hi, does anyone have luck of adding this module into twine's story format? Tried web and local version, both keeps loading and never finish.

**Comment by cauli** [comment]
Apparently Twine made another breaking change on how story formats are imported.

**Comment by cauli** [comment]
https://bitbucket.org/klembot/twinejs/issues/348/twine-21-manual-installation-of-updated

Seems like they are working on fixing this issue. Next release will contain a fix.
 Workaround for now is using a legacy version of twine (offline)

**Comment by tekkkon** [comment]
thanks,  the latest version Twine got it fixed
