### ISSUE TITLE
Undefined is not an object (n.publish) from within publishStory

### ISSUE THREAD

**Issue by lazerwalker** [cauli/TwineJson#2]
I seem to be having some trouble getting this to work. 

I've added it as a story format to my Twine 2 instance as indicated in the README (using http://cau.li/TwineJson/format.js as the URL). Then, in my story file, I've set it to be the story format.

If I try to either play my story (via the "Play" button in the editor) or export it to a file (via the "Publish to File" menu option), it fails out with a JS error, the same one either time. Stack trace attached:

<img width="1429" alt="screen shot 2015-11-12 at 09 45 07" src="https://cloud.githubusercontent.com/assets/821238/11121123/1f7f19b0-8922-11e5-885c-10a7c8a53cb4.png">

Things work as expected with any other story format.

Any thoughts what might be causing this? Might dive into the code and debug myself if you're stumped, but figured I'd make sure this isn't a known issue or anything I'm obviously doing wrong first.

Thanks!

**Comment by cauli** [comment]
@lazerwalker I'll take a look into this one this weekend!
May be related to some minor update on Twine itself.

**Comment by lazerwalker** [comment]
Yeah. I'm having trouble even adding Entweedle as a story format at all, so there having been some recent breaking change to the story format system or some other aspect of Twine seems likely.

**Comment by cauli** [comment]
Filled a simple bug report at Twine2 forums: http://twinery.org/forum/discussion/5107/importing-custom-story-formats-seems-to-be-broken

I recommend you try using an older version of Twine2 for now. Thanks for submitting this issue!

**Comment by lazerwalker** [comment]
For what it's worth, upgrading to the latest Twine 2.0.9 beta seems to have fixed the issue surrounding adding new story formats – I was able to add both this project and Entweedle without any issue. However, this project is still failing, with a different JS error.

**Comment by cauli** [comment]
Ok, the importing issue was completely different from this issue. 

I was able to create a very simple story and export it to .json with no problems.

Let's debug:
- Can you provide an archive of your project or simplified case so that I can try to reproduce it?
- Can you create a very simple story / export it with TwineJson if you still get the error?

**Comment by lazerwalker** [comment]
I made a very simple story (using the hosted web version of Twine 2), and still couldn't get TwineJson to export it. Here it is exported via Harlowe, if you want to import it yourself to reproduce.

https://gist.github.com/lazerwalker/c9b60417b34e71cdb242

Thanks!

**Comment by cauli** [comment]
I was able to export the story, take a look:

https://gist.github.com/cauli/c31f499fe374918429cf

My best guess here is that it is something specific with your browser.
I am using Chrome/Firefox to test it. By the looks of your screenshot you are on Safari?

*\* however *\* the titles using "->" didn't work, and that is related to issue #1

**Comment by lazerwalker** [comment]
I still wasn't able to get it to work using Firefox or Chrome. Are you on a Mac, or could this perhaps be an OS thing?

In any case, I ended up solving this for myself (as so many of us inevitably do in software development) by reinventing the wheel: http://github.com/lazerwalker/twison

**Comment by cauli** [comment]
I am on a Mac, gotta try this on a Windows machine.

Twineson! Cool! I was thinking myself of giving an option o nodes "Primary Keys" to save space / avoid repetition on deeply convoluted trees. Wish I had time to thinker more with this stuff.

I'll link your repo later on the README to give people more options, your solution looks really nice.

**Comment by cauli** [comment]
It looks like this was a bug with Twine itself and has been fixed.
