### ISSUE TITLE
how does the tool work?

### ISSUE THREAD

**Issue by dcsan** [cauli/TwineJson#4]
maybe i can help fix it if you can suggest where to look.

are there any docs on internal memory structures / objects kept by Twine? rather than converting the output it maybe easier to just JSON stringify some of those objects?

otherwise i guess the "format" is able to do some conversion?

**Comment by cauli** [comment]
After you try exporting your file, look at the browser inspector.

You'll get an error message like [this](http://cau.li/TwineJson/bug/saveas.png).

Let's first try to figure out why saveAs is not working (maybe just a _window_.saveAs reference is missing).

Maybe try to print the json as an HTML output into the screen.

**Comment by cauli** [comment]
I think the problem may lie in the fact that now Twine exports the storyboard javascript inside closures, and the saveAs function lies isolated inside one of them

**Comment by dcsan** [comment]
btw twison is broken in chrome, but works in safari. your formatter is broken in both tho (see above issue link)

**Comment by dcsan** [comment]
so i noticed both of your tools just look at the output html and then reformat that as JSON.

surely there's an internal twine data structure somewhere that is being rendered to html, that could be accessed directly instead of reverse engineering the webpage output?

**Comment by lazerwalker** [comment]
These are using an internal Twine data structure. When creating a story format, you're given an XML document embedded within the HTML page (e.g. https://github.com/lazerwalker/twison/blob/master/test/fixture.html, the test fixture I use for Twison) that contains a representation of the game data for you to transform and use as you'd like. 

When you create a story format, you get to specify within your HTML template where the "STORY_DATA" XML blob gets dumped (see: https://github.com/lazerwalker/twison/blob/master/src/storyFormat.html). Even Harlowe, the default story format, operates by reading and transforming this XML.
