### ISSUE TITLE
Unable to add the format

### ISSUE THREAD

**Issue by superprat** [cauli/TwineJson#5]
Twine Mac Version: Version 2.0.10 (2.0.10)

The story format at http://cau.li/TwineJson/format.js could not be added ().

**Comment by superprat** [comment]
Oops, missed that big bold text on the Readme.md file, any idea where I can get an older version of Twine?

**Comment by cauli** [comment]
Over here: https://bitbucket.org/klembot/twinejs/downloads :)

**Comment by superprat** [comment]
What's the last known working version?

**Comment by cauli** [comment]
The exporter works at 2.0.7, but gives an infinite loading activity indicator when adding the story format. It is loaded, nevertheless.

I've uploaded it over here: http://cau.li/TwineJson/Twine-2.0.7

I think 2.0.6 loads the story format without errors.

**Comment by superprat** [comment]
Thanks!

**Comment by superprat** [comment]
Thanks!

**Comment by superprat** [comment]
Thanks!

**Comment by cauli** [comment]
Problem fixed, currently working on version 2.0.11.
