### ISSUE TITLE
export a pure JSON file

### ISSUE THREAD

**Issue by dcsan** [cauli/TwineJson#6]
It seems this tool relies on client side javascript to build a JSON file dynamically.
Is there a way I can get the JSON data from a server side script, without running client side code?

Ideally I want to something like  `curl  $storyUrl`

Or is there a way to just get at the XML twine 'source' of a story that can be transformed offline?

The twine (webUI) has a publishTo File button, so wondering how to trigger that export to happen from a curl or other call..

**Comment by cauli** [comment]
A node.js web service could be created to do this. It is on my plans, but I need some time to work on that.

**Comment by cauli** [comment]
@dcsan Took some time today to create a Node.js CLI tool export published Twine stories.

https://github.com/cauli/twinejson-cli
