### ISSUE TITLE
What was the last working version of Twine this was compatible with?

### ISSUE THREAD

**Issue by HawkenKing** [cauli/TwineJson#7]
Happy to dial back Twine version to get Json output.

**Comment by cauli** [comment]
Hey, HawkenKing.

I developed this story format using 2.0.6, available here: https://bitbucket.org/klembot/twinejs/downloads

2.0.7 works as well, but it gives an ignorable error when loading the Story Format: http://cau.li/TwineJson/Twine-2.0.7

I'm really willing to fix this problem soon. Pull requests are welcomed!

**Comment by dcsan** [comment]
haha @HawkenKing there is a workaround - Twine Mac app saves HTML files to the file system, you can write a transformer for those like an xmlToJson converter.

**Comment by cauli** [comment]
Nice to know. It won't build relations between passages, though. The HTML twine output is quite crude.

**Comment by dcsan** [comment]
what do you mean by relations between passages? the html output includes the links generated in the final output?

**Comment by cauli** [comment]
I mean relations as arrows linking two passages. 

As far as I know, Twine creates the relationships between passages only by describing each passage in plaintex, and then it parses each relation/link in real time (It looks for [[XYZ]] tags inside the content with regex and links to the relating title depending on the Story Format).

My main reason to create TwineJson was to pre-generate the relationships of hierarchy, and that made it easier for me to plug this kind of data into d3.js, for instance.

**Comment by dcsan** [comment]
oh ok, so you need the whole graph?
for myself i'm making a runtime engine, so I only need to know the buttons (links) and where they go. so i think parsing the structured html output is simpler?

**Comment by cauli** [comment]
Exactly.
Probably, yes. : )

**Comment by rlalance** [comment]
What is the likelyhood that this is fixed for the latest twine.
I am evaluating using this to build dialogs and potential quests lines for a game.

**Comment by cauli** [comment]
Problem fixed, currently working on version 2.0.11.
