### ISSUE TITLE
Exporter exports only the first passage

### ISSUE THREAD

**Issue by rlalance** [cauli/TwineJson#8]
![image](https://cloud.githubusercontent.com/assets/1323032/17075241/cfb4ed90-505b-11e6-8cb3-ad8abd2c280d.png)

and here is the resulting export:
`{"id":"3","position":"137,151","name":"Night","content":"[[test|AnotherPassage]]","childrenNames":"[[test|AnotherPassage]]","features":[],"order":[],"children":[]}`

**Comment by cauli** [comment]
Probably related to Issue #1 

Try not using the [[identifier|Title]] syntax for now.

I'll take a look at this bug.

**Comment by cauli** [comment]
Fixed in the current version, 0.1.0.
Thank you for submitting this.

**Comment by rlalance** [comment]
Thank you. This will come handy!
We need this to load the stories into a game in json format :)
