### ISSUE TITLE
Latest export doesn't export

### ISSUE THREAD

**Issue by rlalance** [cauli/TwineJson#9]
Latest export doesn't ask for a destination file and opens a window.
The window doesn't seem to have any json in it.
![image](https://cloud.githubusercontent.com/assets/1323032/17154177/e3f08ca2-534d-11e6-993e-576ded17418d.png)

**Comment by cauli** [comment]
Sorry, I haven't tested the desktop versions of Twine yet, probably a dependency is not loading for some reason.

Can you try exporting on the online version for now?

https://twinery.org/

**Comment by rlalance** [comment]
Will do as soon as I get back home.
Thanks.

**Comment by rlalance** [comment]
Yep, works from web version. Not from the app.

**Comment by cauli** [comment]
Great, thanks for testing it. I'll fix as soon as possible.

**Comment by cauli** [comment]
@richardlalancette I fixed it for OSX desktop, I can't test on a Windows machine right now. If you could that would be great.

0.1.3 also fixes bugs related custom properties '{{foo}}' that were not working and other minor stuff.

**Comment by rlalance** [comment]
Working great on windows now. 
2 save file dialog are opening and they are saved properly.
The 2 type of export are also shown in a window.
Looks like this is completely fixed.
Going to start writting our game stories now, so i'll keep you informed on the status of the exporter :)

Thanks again!

**Comment by cauli** [comment]
Great, I'll be here to help! 💪
